In [2]:
import pandas as pd
import pyarrow.parquet as pq

In [3]:
df = pq.read_table(source='/Users/jeremybellucci/hms-harmful-brain-activity-classification/test_eegs/3911565283.parquet').to_pandas()

In [4]:
df.head()

,Fp1,F3,C3,P3,F7,T3,T5,O1,Fz,Cz,Pz,Fp2,F4,C4,P4,F8,T4,T6,O2,EKG
0,9.210000,-47.459999,15.100000,8.22,-16.900000,-22.99,-25.820000,-10.09,28.370001,-3.01,-27.299999,101.040001,35.110001,14.54,18.33,28.540001,44.090000,69.650002,30.74,171.679993
1,-3.590000,-30.290001,32.380001,10.80,-68.980003,-21.60,-15.080000,-9.21,26.360001,-8.98,-32.279999,95.800003,26.389999,4.82,10.54,20.559999,32.060001,59.439999,23.32,178.279999
2,-26.040001,-60.070000,2.370000,-10.15,-34.689999,-31.40,-31.920000,-26.98,-1.940000,-28.77,-49.770000,73.449997,-3.680000,-17.32,-16.15,-8.270000,5.330000,45.180000,9.49,306.739990
3,-3.040000,-36.250000,29.559999,14.53,-14.010000,-11.90,-14.230000,-6.31,26.040001,-2.77,-25.030001,91.010002,22.610001,6.90,9.93,15.480000,33.580002,69.620003,31.01,223.259995
4,-4.630000,-20.160000,25.190001,1.19,-44.580002,-23.51,-30.709999,-17.60,25.420000,-8.86,-33.959999,89.449997,19.440001,-2.08,6.11,8.380000,24.180000,55.869999,19.91,170.759995